### PR TITLE
Add popup box with ID copy result

### LINKED ISSUE #7: Throw exception to the final user when copying a non-existing `Message-ID`
Fact
===

When copying the `Message-ID` in the test `test-missing.eml` the program does not do nothing and the clipboard maintains its previous content.

Problem
===

When we use this in production, in the rare event we find a message without message-id and the previous message-ids copied were long enough for human-brain-processing this could result in the user "thinking" that it was properly copied when it was not.

Imagine processing a batch of 500 emails with message-Id more or less like this one:

    Message-ID: <42ea82e80db58719b6aa39e85734b890c97d599e.92a0ddd06cac9149304397fec5fac459839a1e6a@some-nice-mail-sender.example.com>

Imagine that in the batch, message 432 does not contain a Message-ID for any reason.

You copy 430 and paste, you copy 431 and paste, you copy 432 and paste, you copy 433 and paste...

Nothing tells you that "copying 432 failed".

Proposed solutions
===

Either one of those two, or both combined:

a) On failure, push a message-box to the user (more elegant, but we must find the way)
b) Put in the clipboard the text `"EXCEPTION: "+ exceptionMessage` (probably easier to implement, but if implemented it will make us "bump" the major if we ever switch to "solution a" and stop putting this message in the clipboard.

I suggest for the messages one of the following.

* If we 100% know the `Message-ID` header is missing:
    ```
    The email message did not contain a Message-ID header
    ```
* If the algorythm failed but we could not find that the reason is that Message-ID is not present, then:
    ```
    Could not copy the Message-ID header. File: xxx, Line: xxx
    ```

I don't know how to push "messageboxes" from an AddOn, but most probably the add-on API must have some kind of way to push alerts to the user (further than console.log which a regular user don't even know what it is).

But if I can help to find how, here I am! Ready to help.

### LINKED ISSUE #8: Provide visual feedback when copy has been completed
Sometimes when software has a "copy" function, it provides a visual feedback that something has been copied to the clipboard.

Here are a few examples:

In a private admin panel
-------------------------
When you  copy, you get a visual "tag" plus a cross-line saying "you aready got this one".
imagen

In StackOverflow
-----------------
When copying a permalink, there's a popup global to the web page.
imagen

In Gitlab
---------
When you copy a commit hash, there's a balloon as a "tooltip"
imagen

In Youtube 
-----------
When you share and "copy the link" there's an animated circle indicating visual "in-place" feedback with a moving shape.
imagen

Common to all of them are two facts:

a) They are "visually very easy to recognize"
b) There's no additional click needed by the user (ie: it's non-interrupting the user flow).

I don't know what options we have in the API.

- If we can force tooltips to show, that could be the easiest solution. Just display "Copied" besides.
- If we don't have tooltips, maybe we could play with the color of the button: Make it green, start a timer to 200ms, on timeout revert to the "default" color.

If we find a solution to this, we could also signal the exception in #7 with an alternative display. For example tooltip "Exception, could not copy" or if we go for the color solution, make it blink in red. In this case this would not be a substitute of the message box, as the exception does really need a user interaction to ensure the user saw it and did not escape to his mind.

Whatever the solution, the visual feedback should be placed in code *after* the placement into the clipboard has succeeded.

### PR DESCRIPTION
**Pull request by garoose**
Resolves #7 and resolves #8 . Adds a fancy popup box that either contains the copied ID on success, or the error information on failure.
copyMessageIDPopup
copyMessageIDPopupError

### CODE REVIEW

**Comment by garoose** [comment]
The error on undefined message-id might be a little confusing for the normal user.. but it should happen rarely enough that I'm not super worried about it. I'm open to feedback, I've never pretended to be a frontend engineer lol.

**Comment by xmontero** [comment]
I will test!!! Thanks!

**Comment by xmontero** [comment]
- Tested and works.
- Code reviewed. I see there are cases I don't know how to test: For example if "zero messages are selected" I won't be able to access to the button, but cool, they are situations catched in the code too!

I think we can merge!

**Comment by garoose** [comment]
Awesome, thanks for your continued support! I had the same inclination about the zero-message-selected case.

**Pull request merged**
