### PR TITLE
Add Raw copy option

### LINKED ISSUE #3: Suggestion: Have config to choose betwen copy "only the message ID value" vs "the full-header"
Hi, Joshua!

I just discovered your extension today and that's exactly what I was looking for during years!

I see that when you click, it puts in the clipboard the **value** of the Message-ID. For example in this header:

    Message-ID: <123456789@some-sender>

the result is to have in the clipboard the string `"123456789@some-sender"`

I have been using the message ID (copying it manually!!) for my CRM entries. For example this could be a regular entry of our everyday usage:

    - Phoned John to 5555555.
    - Answered Voice Mail.
    - Requested tariff by email.
    - Received email with Message-ID: <123456789@some-sender>
    - Received 2 PDFs in the email, the second is corrupt.

I do add the full header, so later on it is easy to scan with regular expressions the full database and find "where emails are referenced" as the structure `*Message-ID: <*>` is not used manually by anyone writing in the CRM.

I wonder (I may help if you direct me, open to contribute) if we could have a "config option" so you set if you want to copy "the value" or "the full header".

In the case of full header we'd end having `"Message-ID: <123456789@some-sender>"` in the clipboard.

I've never coded an extension for thunderbird (nor firefox), but I'm a coder anyway so I'm open to help if you give me the starting point :D

In any case, CONGRATS for your contribution to the world! And thanks!

### PR DESCRIPTION
**Pull request by garoose**
Add option to copy raw message ID label and value with exact case and whitespace. Resolves #3.

### CODE REVIEW

**Comment by xmontero** [comment]
I'm testing it. I'd like to add a set of a few "crafted sample emails" to allow everyone to test this. I find a stopper which is to "commit to git text files which are forced to be downlaoded as binary" to preserve the `CRLF` at the line-endings.

I open a question in StackOverflow here https://stackoverflow.com/questions/61845148/how-to-tell-git-to-preserve-crlf-specifically-for-a-single-set-of-files-mark-a

**Comment by xmontero** [comment]
I think I found two bugs. Not 100% confirmed yet, though.

I have forked the repo. I will make a `test-suite` branch from the `master` instead of the `raw-copy`. I will contribute with a bunch of sample emails I am creating and a comprehensive README.

Let me finish the sample emails and I'll do a PullRequest for the "testing suite". Later on, discussion here will be much easier telling "test xxxxx" is not passing and call them by name.

**Comment by xmontero** [comment]
See PR #6 

After accepting by merging into `master` and then merging back `master` into `raw-copy` you'll easily see a bug showing up.

In the other comment I told that they were 2 bugs, but I feel they are probably the same one. One was that the copy did not work in some cases. The other was that in a multi-line the copy only took 2 from 3 lines.

After more testing I think the thing is that it looses "the last line" in some cases. Therefore "not copying" could be "having one line and loosing the last line which leaves us with nothing".

The test-suite will exhibit that there is "at least" a bug in the new feature that explicitly shows up depending on **if the `Message-ID` header is the last one or not in the headers list before the blank row**. Ie: The relative position of the header inside the header block breaks the algorythm.

I hope the test suite helps!!!

Here, open to help more if you tell me how!

**Comment by garoose** [comment]
Test suite was super helpful, thanks so much! I think I fixed the bugs. Like you said it failed to copy the message ID if it was the last header of the email (it was only looking for newlines but not the end of the string), and then it also failed to copy a subsequent line if started with whitespace besides a space (I assumed it had to be a space).

**Comment by xmontero** [comment]
Fully tested against the test suite.

All okey, with one subtle comment on the "missing". Will open a new issue for that as I think that's not a blocker for this merge.

In short: I think we can safely merge! Thanks so much for your work!

**Comment by xmontero** [comment]
To note that I **only** run the test-suite with the "raw-copy enabled". This is the testing that unblocks this PR and allows it to be merged.

Please note, I did not run the tests with the internal semantic processing of Thunderbird (ie: "raw-copy disabled"), which also could be interesting, but separate from this PR.

**Comment by garoose** [comment]
Great, thanks for your help again. I ran the tests with both normal and raw, and didn't discover anything interesting, besides it removes newlines normally.

**Pull request merged**
