### PR TITLE
Add prefix/suffix options and update to WebExtension

### PR DESCRIPTION
**Pull request by garoose**
This brings the addon into the future by moving away from the
outdated XUL format at the cost of the button being a different
spot, and having to load a full message just to get the header.

This new approach makes a minor change to the default behavior.
The copied message ID now contains the surrounding "<>" which it
didn't before. However, I tested it with git-send-email and it
still works.

This also adds a new options page with the ability to specifiy
a prefix and suffix to go around the Message ID on copy. This
addresses the two pieces feedback I have recieved. It allows
copying the message IDs as gmail links directly, and it allows
copying the full "Message ID: <>" string (#3 ).

### CODE REVIEW

**Comment by garoose** [comment]
@ecrips Hey thanks again for contributing a while ago. I just made some pretty big changes here and was hoping you might help me test and verify them.

**Comment by xmontero** [comment]
@garoose hey! sure, will test... but I don't have a "make" handy (maybe it'll be a good idea to provide a "Dockerfile" to run the make so I'll test it manually. I never installed an add-on manually... where do I have to copy the files? In the "readme" it says "Copy the files to your local extensions directory" but I don't know where it is...

**Comment by xmontero** [comment]
Will try this https://developer.thunderbird.net/add-ons/examples/hello-world-add-on#writing-the-extension method for loading temporary extensions.

**Comment by xmontero** [comment]
Well, I do see the prefix + suffix configuration options there:

imagen

With this configuration I'd expect to have this in the clipboard:

    <BEFORE><some-email-id@blabla>{AFTER}

Nevertheless it does not do the copy well... All the time it copies this literal:

    garoose/copy-message-id/issues/3/625683537@github.com

To ensure it is it putting the content in the clip, I do this:

1. Open a notepad
1. Write `hello`
1. Copy `hello`
1. Paste. See `hello` is pasted.
1. Click on `Copy Message ID` in the Thunderbird toolbar.
1. Paste again in the notepad. I'd expect to see the message ID or `hello` if nothing was placed. But i See `garoose/copy-message-id/issues/3/625683537@github.com` pasted in the notepad.

Can I help more?

**Comment by xmontero** [comment]
By "debugging" the extension:

a) I *can* see the edition boxes (prefix + suffix)
b) I *cannot* find the button!!!

imagen

Where should I click on?

**Comment by garoose** [comment]
Oh I'm glad you found a way to test it, after I logged off last night I realized my README is lacking in terms of install instructions. An unfortunate side effect of the way I managed to add the options into the plugin moved the button to the top right of the client , it should be just out of view on your screenshot there, I'll get a screenshot in a bit.

CopyMessageIDScreenshot

See on the right there? Is that not there for you? What version of TB and what OS are you on?

**Comment by xmontero** [comment]
Something weird happens...

I do see the extension inside. If I click `here Menu | Add-Ons` I see it:

imagen

Nevertheless I don't see any extra button where you say it should be:

imagen

There's nothing to the right of the menu.

Ready to help. Awaiting indications.

**Comment by garoose** [comment]
Ok I think I figured it out, it seems if you've ever customized a toolbar it doesn't automatically add new elements to it. So what you need to do is right click on the toolbar and pick customize, scroll to the bottom of the list and click and drag the Copy Message ID button to where you want it.
Annotation 2020-05-10 162931
Annotation 2020-05-10 163000

**Comment by xmontero** [comment]
Okey!! It works!!

In fact I see the button twice:

imagen

IDK if that's because I do have the "old" add-on installed -although disabled- or what. One button does nothing, the other works as expected according to your design: Prefix+&lt;value&gt;+Suffix.

For example for this configuration,

imagen

I get this in the clipboard:

    Message-Id: <some-code@some-server>

So conclusions:

1. The pull-request itself works. It can be merged.
1. The documentation should reflect your last comment, otherwise the people won't find the button.
1. If I explicitly set the prefix to `Message-Id: ` it will in fact copy that text in the clipboard, but this looses information: Although the headers *may* be set in upper or lower case, this will loose the original header casing. So it works as a workaround and definitively is much better than only having the value but does not exactly close #3 which suggests to copy the full-header. By copying the original line "as is" we would not loose the casing. This can be important in function of the "text-matching" that is expected later when re-using this information. If the matcher matches case-sensitive or byte-per-byte, the loose of information would miss headers sent as `message-id: ` and having in the prefix `Message-Id: `.
1. Finally, I think the previous location of the button was much better. This does not prevent the pull request, as the PR is really very useful. But contextually the PR goes against UX rules. The "Copy Message-ID" action goes associated to "a specific message", so it *should* appear next to the buttons that apply to "this message" like for example "reply", "forward", "delete" and so on.

I'd bet for:

a) Merge the pull-request.
b) Do not close #3.
c) Open a new issue requesting the button to be moved inside the message space.

Can I help more?

**Comment by xmontero** [comment]
Last comment: If you use "semantic versioning", I'd consider those two things a "breaker" of compatibility.

1. The movement of the button to another place. For example a script that "invokes" your button by simulating a click will probably not find it now.
1. The fact that now it copies the &lt; and &gt; signs, in contrast with the previous copy also could disturb someone that has scripted something confident on that the signs were stripped out previously.

Adding prefix/suffix would be really a "minor version bump" if those two other things did not happen. But they happened.

We are (still) only a hundred of users. They all can be "manually controlled" if necessary... but if this grows, semver should be seriously considered. And I think it's easy to start implementing it from the very first versions, if possible, even if there's (still) reduced audience. I really hope this addon gets popular.

This means this version should either lay in the 0.x versions if the first release was still in the 0.x, as those versions are maturing; or either if the first release was 1.x then this one should be bumped to 2.x if you want to follow semver.

IMHO, semver is good :) and should be used if possible. Up to you!

**Comment by xmontero** [comment]
A way to avoid bumping to 2.x and keep it 1.x could be:

Before the PR:

1. Add a checkbox (by default not-checked to ensure compatibility) to select if you want the &lt; and &gt; copied or not. Being an option, you can enable it, but allow old users updating the addon not noticing any change.
1. Find a way to set the button where it was, even if you changed the "technology-stack" behind the way it is implemented.

Then test again, then approve the PR. This could save the major and allow it to still be 1.x.

Let me know if I may help!

**Comment by garoose** [comment]
You raise some excellent points! I appreciate your input. I agree 100% about semantic versioning, I was just being lazy haha. I'll consider your solutions. Reverting to not including the angle-brackets should be easy. Adding the full copy option isn't that hard either now that I have a functioning option pane, I didn't consider different formats for "message-id". The thing that was proving challenging, however, is moving the button back to the message window. I couldn't seem to figure it out. I have nothing against releasing version 2.0 though so maybe I'll put it off like you suggested.

Edit: Actually I'm not sure getting the full ID is so easy. I'm not stripping off the "Message-ID:", it's just not returned by Thunderbird in the first place.

**Comment by garoose** [comment]
I figured out how to move the button to the right toolbar! Check if out when you have time, let me know if it doesn't show up by default again. I sadly don't have an answer for the "copy full ID" problem like I mentioned before, feel free to contribute if you can come up with anything. I don't see any emails in my client that aren't spelled "Message-ID" even so it's hard for me to investigate.

**Comment by xmontero** [comment]
If there's any know forum for add-on developers, I may take the time to ask there. Are you active in any such forum? I may ask "how to get the full-header" there.

**Comment by xmontero** [comment]
Checked this version! All clean to merge:

a) The button appears in the correct place:

imagen

b) The default options are prefix="", suffix="", include-brackets=false, url-encode=false

imagen

I think this gives green light to merge this PR with version 1.x being compatible with semver.

Issue #3 should continues open and the discussion about copying the headers should be continued there, not here.

**Pull request merged**
